AWSTemplateFormatVersion: '2010-09-09'
Description: "Crea un grupo de seguridad que permite trafico SSH desde cualquier IP."

Resources:
  MySecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Permitir trafico SSH desde cualquier direccion IP"
      GroupName: SSHSecurityGroup
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"  

